name: dotnet package

on: workflow_dispatch 

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v5
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: './WateryTart.Platform.Linux/packages.lock.json'
      - name: Install dependencies
        run: dotnet restore
     # - run: dotnet build WateryTart.Platform.Windows/WateryTart.Platform.Windows.csproj
      - run: dotnet publish WateryTart.Platform.Linux -p:PublishProfile=LinuxArm
      - name: Linux-arm64 files
        uses: actions/upload-artifact@v4
        with:           
          path: /home/runner/work/WateryTart/WateryTart/WateryTart.Platform.Linux/bin/release/net10.0/publish/linux-arm64/**
